### ISSUE TITLE
AttributeError: module 'tiffit' has no attribute 'convert'

### ISSUE THREAD

**Issue by zhouyi0812** [EricThomson/tiffit#1]
Hello!
I tried to convert my .tif with tiffit with convert but encountered an error:

AttributeError                            Traceback (most recent call last)
Cell In[17], line 2
      1 import tiffit
----> 2 tiffit.convert('002C5d16_B1_F2_1_00d00h00m.tif', '002C5d16_B1_F2_1_00d00h00m.tiff')

AttributeError: module 'tiffit' has no attribute 'convert'

How should I adjust it?
Thank you very much!

**Comment by EricThomson** [comment]
Hi thanks for the issue. Keep in mind tiffit is a cli (command line interface), so the commands here are at the command line and you use spaces not dots. We discuss this some here: 

https://github.com/flatironinstitute/CaImAn/issues/1189#issuecomment-1774198917

**Comment by zhouyi0812** [comment]
Hello!
I see I see, sorry I forgot about that!
Thank you for your help!!
